# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheWeather
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'

  target 'TheWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheWeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
